name: salary
description: "シンプル給料記録アプリ"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# アプリバージョン番号 + ビルド番号 (+1)部分をインクリメントする
# 以下実行でiOSに反映
# $ flutter build ipa
# リリース手順：https://appdev-room.com/flutter-release
# ビルド等するとキャッシュ等が膨大なので以下コマンドでクリーンにしておく
# $ flutter clean
version: 1.2.3+12

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  realm: ^20.2.0
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  fl_chart: ^0.70.2
  flutter_secure_storage: ^9.2.4
  firebase_core: ^3.13.0
  google_mobile_ads: ^5.3.1
  local_auth: ^2.3.0
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  firebase_analytics: ^11.5.0
  in_app_purchase: ^3.2.3

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# $ flutter pub run flutter_launcher_icons:main
# 上記コマンドを実行してアイコンを自動生成
flutter_icons:
  android: true
  ios: true
  # iOS Lightアイコン
  image_path_ios: "assets/images/app_icon.png"
  # iOS Darkアイコン
  image_path_ios_dark_transparent: "assets/images/app_icon_dark.png"
  # iOS Tintedアイコン
  image_path_ios_tinted_grayscale: "assets/images/app_icon_tinted.png"
  image_path_android: "assets/images/app_icon.png"
  adaptive_icon_background: '#000000'
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_padding: true

flutter:
  uses-material-design: true
